debug = true

defaultEntryPoints = ["https"]

# For secure connection on backend.local
RootCAs = [ "./backend.cert" ]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
       entryPoint = "https"
  [entryPoints.https]
  address = ":4443"
    [entryPoints.https.tls]
     # For secure connection on frontend.local
        [[entryPoints.https.tls.certificates]]
        CertFile = "./frontend.cert"
        KeyFile  = "./frontend.key"


[web]
  address = ":8080"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    # Access on backend with HTTPS
    # url = "https://127.0.0.1:50051"
    url = "https://backend.local:50051"


[frontends]
  [frontends.frontend1]
  backend = "backend1"
  # passHostHeader = true
    [frontends.frontend1.routes.Echo]
    rule = "Host: frontend.local"